on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: placeholder

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Current dir
        run: pwd
      - name: Ls files
        run: ls
      - name: Deploy with rsync
        run: rsync -avz * ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/staging-wordpress/wp-content/themes/astra
