on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: placeholder

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avzO --no-perms * ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/wordpress/wp-content/themes/astra
      - name: Set permissions
        run: ssh -t ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} chgrp -R www-data /var/www/wordpress/wp-content/themes/astra
