on:
  pull_request:
    branches:
      - main
steps:
  - name: Install SSH Key
    uses: shimataro/ssh-key-action@v2
    with:
      key: ${{ secrets.SSH_PRIVATE_KEY }}
      known_hosts: placeholder
  - name: Adding Known Hosts
    run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
  - name: Deploy with rsync
    run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/wordpress/wp-content/themes/test
